opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - HittaTechAssignment/Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - HittaTechAssignment/ThirdPartySource

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

line_length:
  - 160 # warning
  - 200 # error

nesting:
  type_level:
    warning: 2


reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
